version: '3'
services:
  db:
    image: postgres:16
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
#      - ./pgdata/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    healthcheck:
      test: [ "CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5433"

  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
    driver: local